In [38]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from spn.algorithms.LearningWrappers import learn_parametric, learn_classifier
from spn.structure.leaves.parametric.Parametric import Categorical, Gaussian
from spn.structure.Base import Context
from spn.algorithms.MPE import mpe

### Config

In [39]:
use_gpu = False
train_path = '/home/saber/Dropbox/Projects/kaggle/santander/dataset/train.csv'
test_path = '/home/saber/Dropbox/Projects/kaggle/santander/dataset/test.csv'

In [40]:
# Read the CSV into a pandas data frame (df)
dftr = pd.read_csv(train_path, delimiter=',')
train_data = np.array(dftr)
# dfte = pd.read_csv(test_path, delimiter=',')
# test_data = np.array(dfte)

# print(test_data)

In [48]:
#read csv files to arrays and convert types
XX = train_data[:,1:(len(train_data[0]))]
X = np.array(XX[1:200], dtype=np.float)
#TODO: the first column as integer since is the binary class
print(X[0])
X_train, X_test = X[:100000,:], X[100000:,:]

[  0.      11.5006  -4.1473  13.8588   5.389   12.3622   7.0433   5.6208
  16.5338   3.1468   8.0851  -0.4032   8.0585  14.0239   8.4135   5.4345
  13.7003  13.8275 -15.5849   7.8     28.5708   3.4287   2.7407   8.5524
   3.3716   6.9779  13.891  -11.7684  -2.5586   5.0464   0.5481  -9.2987
   7.8755   1.2859  19.371   11.3702   0.7399   2.7995   5.8434  10.816
   3.6783 -11.1147   1.873    9.8775  11.7842   1.2444 -47.3797   7.3718
   0.1948  34.4014  25.7037  11.8343  13.2256  -4.1083   6.6885  -8.0946
  18.5995  19.3219   7.0118   1.921    8.8682   8.0109  -7.2417   1.7944
  -1.3147   8.1042   1.5365   5.4007   7.9344   5.022    2.2302  40.5632
   0.5134   3.1701  20.1068   7.7841   7.0529   3.2709  23.4822   5.5075
  13.7814   2.5462  18.1782   0.3683  -4.821   -5.485   13.7867 -13.5901
  11.0993   7.9022  12.2301   0.4768   6.8852   8.0905  10.9631  11.7569
  -1.2722  24.7876  26.6881   1.8944   0.6939 -13.695    8.4068  35.4734
   1.7093  15.1866   2.6227   7.3412  32.0888  13.95

In [49]:
t = [Categorical]
for i in range(200):
	t.append(Gaussian)
#Learning on train data
spn_classification = learn_classifier(X,
                       Context(parametric_types=t).add_domains(X_train),
                       learn_parametric, 0)

In [51]:
# TT = test_data[:,1:(len(test_data[0]))]
# R = test_data[:,[0]]
print(X_test[0])
print(X_train[0])

IndexError: index 0 is out of bounds for axis 0 with size 0

In [44]:
# T = np.array(TT, dtype=np.float)
nan = np.array([[np.nan]]*200000)
T = np.append(nan,X_test,axis=1)
test_classification = T

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [13]:
mpe_classes = mpe(spn_classification, test_classification)

In [14]:
print(mpe_classes)

[[  0.      11.0656   7.7798 ...  10.72    15.4722  -8.7197]
 [  0.       8.5304   1.2543 ...   9.8714  19.1293 -20.976 ]
 [  0.       5.4827 -10.3581 ...   7.0618  19.8956 -23.1794]
 ...
 [  0.      11.636    2.2769 ...   9.1933  11.7905 -22.2762]
 [  0.      13.5745  -0.5134 ...   8.1079   8.7735  -0.2122]
 [  0.      10.4664   1.807  ...  10.3378  14.334   -7.7094]]


In [24]:
count = 0
for i in mpe_classes:
    if (i[0] == 1.0):
        count+=1

print(len(mpe_classes))
print(count)
    
#     if (str(i[0]) =="1.0"):
#         print(i)

200000
237


In [25]:
print(len(test_data))

200000


In [34]:
print(train_data[0])

['train_0' 0 8.9255 -6.7863 11.9081 5.093 11.4607 -9.2834 5.1187 18.6266
 -4.92 5.747000000000001 2.9252 3.1821 14.0137 0.5745 8.7989 14.5691
 5.7487 -7.2393 4.284 30.7133 10.535 16.2191 2.5791 2.4716 14.3831 13.4325
 -5.1488 -0.4073 4.9306 5.9965 -0.3085 12.9041 -3.8766 16.8911 11.192
 10.5785 0.6764 7.8871 4.6667 3.8743 -5.2387 7.3746 11.5767 12.0446
 11.6418 -7.017 5.9226 -14.2136 16.0283 5.3253 12.9194 29.046
 -0.6940000000000001 5.1736 -0.7474 14.8322 11.2668 5.3822 2.0183 10.1166
 16.1828 4.959 2.0771 -0.2154 8.6748 9.5319 5.8056 22.4321 5.0109
 -4.7010000000000005 21.6374 0.5663 5.1999 8.86 43.1127 18.3816 -2.344
 23.4104 6.5199 12.1983 13.6468 13.8372 1.3675 2.9423 -4.5213 21.4669
 9.3225 16.4597 7.9984 -1.7069 -21.4494 6.7806 11.0924 9.9913 14.8421
 0.1812 8.9642 16.2572 2.1743 -3.4132 9.4763 13.3102 26.5376 1.4403 14.71
 6.0454 9.5426 17.1554 14.1104 24.3627 2.0323 6.7602 3.9141 -0.4851 2.524
 1.5093 2.5516 15.5752 -13.4221 7.2739 16.0094 9.7268 0.8897 0.7754 4.2218
 12.0039 